/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    artifacts: Artifact;
    'catalog-entries': CatalogEntry;
    reviews: Review;
    'audit-log': AuditLog;
    'discovery-sources': DiscoverySource;
    'discovery-runs': DiscoveryRun;
    news: News;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    artifacts: ArtifactsSelect<false> | ArtifactsSelect<true>;
    'catalog-entries': CatalogEntriesSelect<false> | CatalogEntriesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'discovery-sources': DiscoverySourcesSelect<false> | DiscoverySourcesSelect<true>;
    'discovery-runs': DiscoveryRunsSelect<false> | DiscoveryRunsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  entraOid: string;
  email: string;
  name?: string | null;
  tenantId?: string | null;
  role: 'reader' | 'contributor' | 'reviewer' | 'approver' | 'admin';
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artifacts".
 */
export interface Artifact {
  id: number;
  artifactId: string;
  type: 'skill' | 'prompt' | 'workflow' | 'mcp' | 'template' | 'policy' | 'playbook';
  name: string;
  description: string;
  version: string;
  owner?: {
    team?: string | null;
    contact?: string | null;
  };
  source?: {
    provider?: string | null;
    repository?: string | null;
    path?: string | null;
  };
  installCommand?: string | null;
  readme?: string | null;
  tags?: string[] | null;
  visibility?: ('internal' | 'public' | 'restricted') | null;
  lifecycleStatus?:
    ('draft' | 'experimental' | 'in-review' | 'approved' | 'recommended' | 'deprecated' | 'archived') | null;
  active?: boolean | null;
  lastIndexedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-entries".
 */
export interface CatalogEntry {
  id: number;
  artifact: number | Artifact;
  businessOwner?: string | null;
  technicalOwner?: string | null;
  riskLevel?: ('low' | 'medium' | 'high') | null;
  reviewStatus?: ('not-submitted' | 'in-review') | null;
  approvalState?: ('not-approved' | 'approved' | 'rejected') | null;
  lifecycleState: 'draft' | 'experimental' | 'in-review' | 'approved' | 'recommended' | 'deprecated' | 'archived';
  recommended?: boolean | null;
  featured?: boolean | null;
  internalNotes?: string | null;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  artifact: number | Artifact;
  type: 'security' | 'privacy-gdpr' | 'technical' | 'accessibility' | 'responsible-ai' | 'operational';
  reviewer?: (number | null) | User;
  status?: ('pending' | 'completed') | null;
  decision?: ('approved' | 'changes-requested' | 'rejected') | null;
  comments?: string | null;
  requiredChanges?: string | null;
  riskLevel?: ('low' | 'medium' | 'high') | null;
  reviewDate?: string | null;
  expiryDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  actor: number | User;
  action: 'metadata-edit' | 'lifecycle-transition' | 'review-recorded' | 'approval-decision' | 'role-change';
  artifact?: (number | null) | Artifact;
  targetUser?: (number | null) | User;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discovery-sources".
 */
export interface DiscoverySource {
  id: number;
  name: string;
  repo: string;
  ref?: string | null;
  /**
   * Name of the env var holding the GitHub token (value never stored here).
   */
  tokenEnvVar: string;
  webhookSecret: string;
  enabled?: boolean | null;
  /**
   * Per-source run lock; set while a run is in progress.
   */
  runningSince?: string | null;
  lastRunAt?: string | null;
  lastRunOutcome?: ('success' | 'failure') | null;
  lastRunSummary?: {
    created?: number | null;
    updated?: number | null;
    deactivated?: number | null;
    skippedInvalid?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discovery-runs".
 */
export interface DiscoveryRun {
  id: number;
  source: number | DiscoverySource;
  trigger: 'webhook' | 'scheduled' | 'manual';
  triggeredBy?: (number | null) | User;
  startedAt: string;
  finishedAt?: string | null;
  outcome: 'success' | 'failure';
  failureReason?: string | null;
  summary?: {
    created?: number | null;
    updated?: number | null;
    deactivated?: number | null;
    duplicates?: number | null;
    skippedInvalid?: number | null;
  };
  createdIds?: string[] | null;
  updatedIds?: string[] | null;
  deactivatedIds?: string[] | null;
  skippedInvalid?:
    | {
        path?: string | null;
        errors?: string[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL handle (/news/<slug>); auto-derived from the title when left blank.
   */
  slug?: string | null;
  /**
   * Short preview shown in the employee news list.
   */
  summary?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  status: 'draft' | 'published';
  publishDate?: string | null;
  tags?: string[] | null;
  heroImageUrl?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL handle (/events/<slug>); auto-derived from the title when left blank.
   */
  slug?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * When the event starts (Europe/Oslo).
   */
  startDateTime: string;
  /**
   * Optional end; must not be before the start.
   */
  endDateTime?: string | null;
  /**
   * Free-text place (optional).
   */
  location?: string | null;
  /**
   * Optional online-meeting link.
   */
  onlineUrl?: string | null;
  /**
   * Who runs the event — a person, team, or external party (free text).
   */
  organizer?: string | null;
  status: 'draft' | 'published';
  tags?: string[] | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'artifacts';
        value: number | Artifact;
      } | null)
    | ({
        relationTo: 'catalog-entries';
        value: number | CatalogEntry;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'discovery-sources';
        value: number | DiscoverySource;
      } | null)
    | ({
        relationTo: 'discovery-runs';
        value: number | DiscoveryRun;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  entraOid?: T;
  email?: T;
  name?: T;
  tenantId?: T;
  role?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artifacts_select".
 */
export interface ArtifactsSelect<T extends boolean = true> {
  artifactId?: T;
  type?: T;
  name?: T;
  description?: T;
  version?: T;
  owner?:
    | T
    | {
        team?: T;
        contact?: T;
      };
  source?:
    | T
    | {
        provider?: T;
        repository?: T;
        path?: T;
      };
  installCommand?: T;
  readme?: T;
  tags?: T;
  visibility?: T;
  lifecycleStatus?: T;
  active?: T;
  lastIndexedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-entries_select".
 */
export interface CatalogEntriesSelect<T extends boolean = true> {
  artifact?: T;
  businessOwner?: T;
  technicalOwner?: T;
  riskLevel?: T;
  reviewStatus?: T;
  approvalState?: T;
  lifecycleState?: T;
  recommended?: T;
  featured?: T;
  internalNotes?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  artifact?: T;
  type?: T;
  reviewer?: T;
  status?: T;
  decision?: T;
  comments?: T;
  requiredChanges?: T;
  riskLevel?: T;
  reviewDate?: T;
  expiryDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  artifact?: T;
  targetUser?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discovery-sources_select".
 */
export interface DiscoverySourcesSelect<T extends boolean = true> {
  name?: T;
  repo?: T;
  ref?: T;
  tokenEnvVar?: T;
  webhookSecret?: T;
  enabled?: T;
  runningSince?: T;
  lastRunAt?: T;
  lastRunOutcome?: T;
  lastRunSummary?:
    | T
    | {
        created?: T;
        updated?: T;
        deactivated?: T;
        skippedInvalid?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discovery-runs_select".
 */
export interface DiscoveryRunsSelect<T extends boolean = true> {
  source?: T;
  trigger?: T;
  triggeredBy?: T;
  startedAt?: T;
  finishedAt?: T;
  outcome?: T;
  failureReason?: T;
  summary?:
    | T
    | {
        created?: T;
        updated?: T;
        deactivated?: T;
        duplicates?: T;
        skippedInvalid?: T;
      };
  createdIds?: T;
  updatedIds?: T;
  deactivatedIds?: T;
  skippedInvalid?:
    | T
    | {
        path?: T;
        errors?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  author?: T;
  status?: T;
  publishDate?: T;
  tags?: T;
  heroImageUrl?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  startDateTime?: T;
  endDateTime?: T;
  location?: T;
  onlineUrl?: T;
  organizer?: T;
  status?: T;
  tags?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}